### PR TITLE
Changes for usage in tile-grid

### PR DESCRIPTION
**Pull request by pka**
These are the changes I made for using ogcapi-types it in https://github.com/pka/tile-grid, but there is some cleanup needed, bevore it can be integrated.

### CODE REVIEW

**Review by b4l — CHANGES_REQUESTED** [review]
@pka thank you for the pr! some files in the `common` module show up as empty which seems odd. apart from this, it's good to go.

**Comment by pka** [comment]
> some files in the `common` module show up as empty which seems odd. apart from this, it's good to go.

I've removed the executable flag of these source files.

**Comment by pka** [comment]
The remaining test failure looks like a setup problem:

```
test edr ... FAILED

failures:

---- edr stdout ----
Error: service error

Caused by:
    0: unhandled error
    1: unhandled error
    2: Error { code: "AccessDenied", message: "Access Denied.", request_id: "1778C5E05A035C33", s3_extended_request_id: "dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8" }
```

**Comment by b4l** [comment]
@pka thanks for the clippy lints! fixed the test in https://github.com/georust/ogcapi/pull/18/commits/9f15439e479ee35c28031aa7b9c9d5393dfd2b21.

**Review by b4l — APPROVED** [review]

**Pull request merged**
